language: go
go:
- '1.11'
services:
- docker
sudo: required

install:
- go get -u golang.org/x/lint/golint
# - git submodule update --init

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
- make testenv

script:
- diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
- diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
- go test -race -short -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)